#!/usr/bin/python2
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import shutil
import tempfile
import daemon
import logging
from gi.repository import GLib
from dbus.mainloop.glib import DBusGMainLoop

sys.path.append('/usr/lib/selfnetd')
from sn_subcmd import SnSubCmdMain

param = SnParam()
parseResult = SnCommandArgument()

# some assistant sub command
if parseResult.subcmd == "generate_ca_cert":
	SnSubCmdMain(param).generateCaCert()
	sys.exit(0)
elif parseResult.subcmd == "generate_cert":
	SnSubCmdMain(param).generateCert(parseResult.hostname, parseResult.out_dir, parseResult.export)
	sys.exit(0)
else:
	assert parseResult.subcmd == ""
